alwaysReplace: true
caseSensitive: true
customLabels:
  - text: 'fix'
    label: 'fix'
  - text: 'feature'
    label: 'feature'
  - text: 'feat'
    label: 'feature'
searchBody: true
searchTitle: true
