before:
  hooks:
    - go mod tidy
builds:
  - id: "sonic-ios-bridge"
    main: .
    binary: sib
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
archives:
  - replacements:
      darwin: macosx
      linux: linux
      windows: windows
      386: x86
      amd64: x86_64
