before:
  hooks:
    - go mod tidy
builds:
  - id: "sonic-ios-bridge"
    main: .
    binary: sib
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
